# Generated by Django 3.2.5 on 2021-08-12 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sudoku', models.TextField()),
                ('num_moves', models.IntegerField(blank=True, null=True)),
                ('solution', models.TextField()),
                ('solved', models.BooleanField(default=False)),
                ('solve_time', models.DurationField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 13, 22, 40, 4385), null=True)),
            ],
        ),
    ]
