# Generated by Django 3.2.5 on 2021-08-12 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 13, 22, 51, 667971), null=True),
        ),
    ]
