# Generated by Django 3.2.5 on 2021-08-13 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_score_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date',
        ),
        migrations.AddField(
            model_name='score',
            name='run_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 8, 59, 7, 10502), null=True),
        ),
    ]
