# Generated by Django 3.2.5 on 2021-08-17 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20210813_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='num_moves',
        ),
        migrations.RemoveField(
            model_name='score',
            name='solve_time',
        ),
        migrations.AlterField(
            model_name='score',
            name='run_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 12, 44, 32, 29289), null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='solved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
