# Generated by Django 3.2.5 on 2021-08-17 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20210817_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='run_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 12, 59, 41, 823946), null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='solution',
            field=models.CharField(max_length=81),
        ),
        migrations.AlterField(
            model_name='score',
            name='sudoku',
            field=models.CharField(max_length=81),
        ),
    ]
